#!/usr/bin/env bash
# Install nginx ang configure to return "Hello World!"
if ! [ -x "$(command -v nginx)" ]; then
	sudo apt-get -y update
	sudo apt-get -y install nginx
fi

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx restart
