#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
if ! [ -x "$(command -v nginx)" ]; then
	sudo apt-get -y update
	sudo apt-get -y install nginx
fi

sudo echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i "/server_name _;/a \    location /redirect_me {\n        return 301 https://www3.ntu.edu.sg/home/ehchua/programming/webprogramming/HTTP_Basics.html;\n    }" /etc/nginx/sites-available/default

service nginx restart
