#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely
# and I am invincible!!! when recieving a SIGTERM signal

while true
do
	trap 'echo "I am invincible!!!"' SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
