#!/usr/bin/env bash
# script that displays "Best School" 10 times and hi in the 9th using while and if
counter=1
while [ $counter -le 20 ]
do
	echo $counter
	case $counter in 
		4)
			echo "bad luck from China"
			;;
		8)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((counter++))
done

