#!/usr/bin/env bash
# script that displays "Best School" 10 times and hi in the 9th using while and if
counter=1
while [ $counter -le 20 ]
do
	echo $counter
	if [ $counter -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $counter -eq 8 ]
	then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]
	then 
		echo "bad luck from Italy"
	fi
	((counter++))
done

