#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hour=0
minute=1
while [ $hour -le 12 ]
do
minute=1
	while [ $minute -le 59 ]
	do
		if [ $minute -eq 1 ]
		then
			echo Hour: $hour
		fi
	echo $minute
	((minute++))
	done
((hour++))
done

